baseurl: "/darwinbuild"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
permalink: pretty
title: "Darwinbuild"
url: "https://macosforge.github.io"
